### PR TITLE
Added explanations for core shape failures

### PR DESCRIPTION
**Pull request by goodb**
Looks like this:
```json
"violations": [
          {
            "explanations": [
              {
                "shape_id": "http://purl.obolibrary.org/obo/go/shapes/MolecularFunction",
                "constraints": [
                  {
                    "target_node_uri": "http://model.geneontology.org/R-HSA-73930/R-HSA-73930",
                    "property_id": "http://purl.obolibrary.org/obo/RO_0002413",
                    "intended_range_shapes": [
                      "http://purl.obolibrary.org/obo/go/shapes/MolecularFunction"
                    ]
                  }
                ]
              }
            ],
            "node_id": "http://model.geneontology.org/R-HSA-73930/R-HSA-110360",
            "commentary": "http://model.geneontology.org/R-HSA-73930/R-HSA-110360 did not match http://purl.obolibrary.org/obo/go/shapes/MolecularFunction"
          }
        ]
      }
    ],
```

### CODE REVIEW

**Comment by kltm** [comment]
This is looking really good to me!

I have a couple of questions/thoughts on trying to bring it a little closer to the current wire format (e.g. https://github.com/berkeleybop/bbop-graph-noctua/blob/master/tests/minerva-09.json , https://github.com/berkeleybop/bbop-response-barista/blob/master/tests/response-gomodel-55ad81df00000001-action-2016-11-01.json).

* generally, hyphens over underscores
* CURIEs over URIs (except, oddly, ORCIDs); generally, the clients have been dealing with the CURIEs and the the graphs are currently using CURIEs for the identifiers for the various nodes, relations, etc.; I'm guessing there is no mapping for the shapes at this point
* generally, the pattern X_id is not used, either just X, or just id when not ambiguous
* object over target

This new version is without the fields like rule, tracker, etc. Do you feel this is expressive enough, or a waypoint?

Tagging #212

**Comment by goodb** [comment]
@kltm 

- generally, hyphens over underscores

The objects are automatically generated from Java classes.  Since Java variables can't have hyphens this is a bit of a pain.  Its not impossible, just a hassle.  Let me know if this is important or not.  

 - CURIEs over URIs (except, oddly, ORCIDs); generally, the clients have been dealing with the CURIEs and the the graphs are currently using CURIEs for the identifiers for the various nodes, relations, etc.; I'm guessing there is no mapping for the shapes at this point

Similarly, all of the code involved here (libraries for OWL, RDF, Shex) uses URIs exclusively.  We can convert to curies in output layers (and I think there is already code in Minerva to help with that) but my druthers would be to live in URI land throughout.  Likewise, let me know priority for you.  
Yes, no official curie mapping for shapes, though it wouldn't be hard to imagine what it would look like.  

 - generally, the pattern X_id is not used, either just X, or just id when not ambiguous

Okay, can do.  
 - object over target

Okay
- This new version is without the fields like rule, tracker, etc.

Those fields are all still there, they are just up a level from the object you see in here.  Adding in the full response here:

[SampleM3BatchResponseWithValidationExplanation.json.txt](https://github.com/geneontology/minerva/files/3576921/SampleM3BatchResponseWithValidationExplanation.json.txt)

-  Do you feel this is expressive enough, or a waypoint?
Yes, I think it is.  You could do a lot in the UI with this information (as well as the supertypes on the individuals).  There are elements of the schema that won't show up in the validation report and explanation yet, like the reference stuff that @balhoff just added, but I think this is still a big step forward.  A sound and complete explanation system for this stuff could get very complicated.. but we can do a lot with chunks like this one.

**Comment by goodb** [comment]
@kltm Unless you are actively working with this, I'm going to fiddle with names this morning per your response - will push into this same branch.

**Comment by goodb** [comment]
After last syntax changes, relevant part of the response looks like:
 "model_title": "GO_shapes Activity unit test 20",
        "conformant": false,
        "tracker": "https://github.com/geneontology/go-shapes/issues",
        "rulefile": "https://github.com/geneontology/go-shapes/blob/master/shapes/go-cam-shapes.shex",
        "violations": [
          {
            "explanations": [
              {
                "shape": "http://purl.obolibrary.org/obo/go/shapes/MolecularFunction",
                "constraints": [
                  {
                    "object": "gomodel:5d27d1cf00000444/5d27d1cf00000446",
                    "property": "RO:0002333",
                    "intended_range_shapes": [
                      "http://purl.obolibrary.org/obo/go/shapes/ProteinContainingComplex",
                      "http://purl.obolibrary.org/obo/go/shapes/InformationBiomacromolecule"
                    ]
                  },
                  {
                    "object": "gomodel:5d27d1cf00000444/5d29218800000055",
                    "property": "RO:0002092",
                    "intended_range_shapes": [
                      "http://purl.obolibrary.org/obo/go/shapes/PlantStructureDevelopmentStage",
                      "http://purl.obolibrary.org/obo/go/shapes/BiologicalPhase",
                      "http://purl.obolibrary.org/obo/go/shapes/LifeCycleStage"
                    ]
                  },
                  {
                    "object": "gomodel:5d27d1cf00000444/5d27d1cf00000445",
                    "property": "RO:0002234",
                    "intended_range_shapes": [
                      "http://purl.obolibrary.org/obo/go/shapes/ChemicalEntity",
                      "http://purl.obolibrary.org/obo/go/shapes/ProteinContainingComplex"
                    ]
                  },
                  {
                    "object": "gomodel:5d27d1cf00000444/5d27d1cf00000453",
                    "property": "RO:0002233",
                    "intended_range_shapes": [
                      "http://purl.obolibrary.org/obo/go/shapes/ChemicalEntity",
                      "http://purl.obolibrary.org/obo/go/shapes/ProteinContainingComplex"
                    ]
                  },
                  {
                    "object": "gomodel:5d27d1cf00000444/5d27d1cf00000459",
                    "property": "RO:0002413",
                    "intended_range_shapes": [
                      "http://purl.obolibrary.org/obo/go/shapes/MolecularFunction"
                    ]
                  }
                ]
              }
            ],
            "node": "gomodel:5d27d1cf00000444/5d27d1cf00000449",

**Comment by kltm** [comment]
This is in response to looking at https://github.com/geneontology/minerva/files/3581126/SampleM3BatchResponseWithValidationExplanation.json.txt

* Great on the switch to CURIEs
* `validation-results` appears to be an array; the array appears to be a list of various "types". If the order is fixed, it would probably be better to make them object.
* I'm a little unsure of `node_report`, `model_report`, and `commentary`. They appear to be semi-structured text blobs that may be awkward for a client to render. Are these the explanation of last resort, or are they meant to be further processed by the client? The earlier version seemed to be more compact and readable.
* (small) `conformant` would be more similar if it was `is-conformant` or `conformant-p` (wish we had been more careful in the past, so whatever)
* for "_" vs "-", Heiko also had a problem with it, but he found a solution (higher up in the reposne handler, IIRC). You might want to check what he did and see if it applies. If not, that is a judgement call for you; my druthers is for "-", but not enough to derail other development.

**Comment by goodb** [comment]
> This is in response to looking at https://github.com/geneontology/minerva/files/3581126/SampleM3BatchResponseWithValidationExplanation.json.txt
> 
> * Great on the switch to CURIEs
> * `validation-results` appears to be an array; the array appears to be a list of various "types". If the order is fixed, it would probably be better to make them object.

It is an array containing validation report objects.  Currently there will always be one that is for the OWLReasoner validation and one that is for the Shex validation report.  We could add new elements for other regimes, e.g. go rules.  (These both extend the root validation report object).  Not sure what you mean by 'make them object'.  Could you write down an example of the json structure you are thinking here?

> * I'm a little unsure of `node_report`, `model_report`, and `commentary`. They appear to be semi-structured text blobs that may be awkward for a client to render. Are these the explanation of last resort, or are they meant to be further processed by the client? The earlier version seemed to be more compact and readable.

It might make sense to just completely take these out for Minerva.  The client should be able to do a much better job given the structured data in the response and its access to visual elements.  It has everything needed to make these blobs if desired.  These are larger than the previous version as they incorporate more information about why a given shape did not match.  (They look okay on a command line.)  

> * (small) `conformant` would be more similar if it was `is-conformant` or `conformant-p` (wish we had been more careful in the past, so whatever)

There is a noncomformant-p parameter at the top level of the data object that expresses whether or not any of the validation systems found a problem.  The -p suffix seems to be a pattern that Heiko added on to variables he was explicitly playing with in the final json generator step.  I don't know what else it means.  

> * for "_" vs "-", Heiko also had a problem with it, but he found a solution (higher up in the reposne handler, IIRC). You might want to check what he did and see if it applies. If not, that is a judgement call for you; my druthers is for "-", but not enough to derail other development.

**Comment by goodb** [comment]
@kltm I think I addressed all your concerns above, including the object/array question.  Object attached.  It might be worth going over in voice to be sure the explanation data from shex makes sense.  
(Note this also contains all the super types on all the individuals in the data.individuals.inferred-type-with-all field - let me know if you want any changes there.)
Turns out variable renaming for json is easy after all thanks to gson.  Now you have your precious hyphens ;).  

[SampleM3BatchResponseWithValidationExplanation.json.txt](https://github.com/geneontology/minerva/files/3582235/SampleM3BatchResponseWithValidationExplanation.json.txt)

**Comment by kltm** [comment]
@goodb 
I'm glad the hyphens worked out--I'll never admit how much that was going to eat away at me.

Over, this is really looking great to me.

Some small points or questions:

* `noncomformant-p` and then below we have `is-conformant`, unless there is a reason I'm missing, those should probably be the same as far as default positivity goes; also, the same marker for predicate would be nice as they are the same thing; actually, are both necessary?
* commentary / human-readable explanations now out <- neutral, just noting the change here; this means that the clients should have a common lib to make something usable
* `node-matched-shapes` is what each individual was qualified against, right?
* noting existence of  `inferred-type-with-all` in individuals. Is it the complete closure, or a subset? I had thought that the "biolink type" was a subset, but I may have read that wrong.

Happy to continue here or voice talk, at your convenience.

**Comment by goodb** [comment]
> * `noncomformant-p` and then below we have `is-conformant`, unless there is a reason I'm missing, those should probably be the same as far as default positivity goes; also, the same marker for predicate would be nice as they are the same thing; actually, are both necessary?

The nonconformant-p flag is modeled directly after the inconsistent-p flag.  Agree its default positivity is confusing.  It does serve a useful purpose.  It indicates whether or not any of the validation regimes failed without need to inspect all of them.  Maybe switch to is-comformant-p and switch the boolean ?

> * commentary / human-readable explanations now out <- neutral, just noting the change here; this means that the clients should have a common lib to make something usable

I think it makes sense to move the job of turning the structured explanation content into something useful to a human to the client as the client has access to all of the important tools.  It would be trivial to generate the logic for building the text explanation I started out with in the javascript if that is desired, but I hope we have something much more elegant.  

> * `node-matched-shapes` is what each individual was qualified against, right?

Yes, for each node it gives a list of the shapes it matched against.  Note that this is not exhaustive (as it stands).  Not every shape is tested against every node.  It may be useful for building explanations to do a more thorough matching, but that can come later.  

> * noting existence of  `inferred-type-with-all` in individuals. Is it the complete closure, or a subset? I had thought that the "biolink type" was a subset, but I may have read that wrong.

That is the complete closure - all inferred types.  So far no attempt has been map from these classes to biolink types within minerva.

**Comment by kltm** [comment]
`Maybe switch to is-comformant-p and switch the boolean ?`
How about `is-conformant` to fit the next variable down, which is also `is-conformant`?

To clarify on the `inferred-type-with-all`, is there a separate desire for the full closure, or is this step towards testing out and using what we will get for https://github.com/geneontology/minerva/issues/217

**Comment by goodb** [comment]
> `Maybe switch to is-comformant-p and switch the boolean ?`
> How about `is-conformant` to fit the next variable down, which is also `is-conformant`?

Sure, not really sure what the -p is there for in any case.  Maybe it would be better to move it inside the validation-results object at its top level.  

> To clarify on the `inferred-type-with-all`, is there a separate desire for the full closure, or is this step towards testing out and using what we will get for #217

This is meant to address #217 .  I don't know of any other desire for full closure on types.   I think it could serve the purpose as is, without actually providing the BL types.  I think the use case here is analogous to the use case within the shex schema.  In the schema, the idea of using the BL types was dropped midsummer, while I was away, in favor of using the full subclass closure to figure out what is what.  Though @cmungall and @balhoff should be able to explain more, one thing you clearly gain from that is the ability to use different levels of the hierarchies as you see fit rather than being tied to the more simplistic upper level categories.

**Comment by kltm** [comment]
---

Noting that "noncomformant-p" has the "conformant" part misspelled (m for n); I've been cutting and pasting that everywhere so don't pick up the field name from me.

Currently, there's:

 .data.noncomformant-p
 .data.validation-results.is-conformant
 .data.validation-results.shex-validation.is-conformant

It would seem to me that the top-level is the most useful one, so maybe just:

.data.is-conformant 

?

---

For #217 , would you be referring to switching over to just the closure here: https://github.com/geneontology/minerva/issues/217#issuecomment-523987168 ? If chris has signed off on this that's all fine, but we should probably change the ticket more clearly so I don't pester you as I catch up ;)

---

**Comment by goodb** [comment]
> .data.noncomformant-p
> .data.validation-results.is-conformant
> .data.validation-results.shex-validation.is-conformant
> 
> It would seem to me that the top-level is the most useful one, so maybe just:
> 
> .data.is-conformant
> 
> ?

I'm basing my thinking on the idea that we want to be able to fairly easily add new validation regimes into this system.  Right now we sort of have two - with work needed for OWL explanations.  Given that, I think we should have both a top level is-conformant parameter that indicates whether all is good or not and we should also have validation-regime-specific is-conformant fields to indicate whether each regime is happy.  e.g. We often have cases where OWL is consistent ("conformant" in this way of thinking) but shex is not.  

> For #217 , would you be referring to switching over to just the closure here: [#217 (comment)](https://github.com/geneontology/minerva/issues/217#issuecomment-523987168) ? If chris has signed off on this that's all fine, but we should probably change the ticket more clearly so I don't pester you as I catch up ;)

Yes, I think we might want to just switch over to the full closure here.  It would solve tremayne's problem here.  But I have not discussed anything with @cmungall .  Unless there is some external reason to do biolink I guess I'm not really sure what it buys us within this specific project.  

I'm pretty happy with this structure.  Does the violation/explanation/constraint part make sense to you?
[Uploading SampleM3BatchResponseWithValidationExplanation.json.txt…]()

**Comment by kltm** [comment]
Re: `is-conformant` Sounds great.

The last I heard is that we were doing biolink, not full closure, although that would work in Tremayne's use case as well (although some additional map probing would be added, either in the API or manually). Either way, I think this is fine to move forward for testing, with maybe a final round of discussion about the strategy when Chris gets back online.

The last upload "Uploading SampleM3BatchResponseWithValidationExplanation.json.txt…" seems to have failed--it appears as a link to another ticket for me.

**Comment by goodb** [comment]
I believe I fixed the uploaded file in an edit to the comment above.

**Comment by goodb** [comment]
Regarding biolink I think that we need to have a coherent strategy across all the different GO projects.  In particular the shex schema work should be in alignment with whatever we are doing in Minerva. We want one place where the ontology term to schema category mappings are maintained that we can all draw from.

**Comment by kltm** [comment]
Okay, looking at results.

Top level lists not conformant, so probe `owl-validation` and `shex-validation`, find the latter is a problem. Walk through list of `violations`, highlighting on node. In future, decode the explanation a bit, trying to let the user know which constraint was violated.
Seems reasonable.

Re: biolink, I agree that a strategy is needed. We'll still be in the air until Chris gets back at the end of the month-ish, so we should just plow forward with the testing in the interim.

I think we're all good here, yes? I'm ready to take the PR is you'd like.

**Comment by goodb** [comment]
All set..  hope this moves the ball forward!

**Pull request merged**
