### PR TITLE
add located_in and is_active_in to allowed list of relations fixes #385

### LINKED ISSUE #385: add is_active_in and located_in
http://noctua-dev.berkeleybop.org/editor/graph/gomodel:ZFIN_ZDB-GENE-990415-160 is not pushed out in the noctua-gpad file.

@dustine32 discovered two relations that need to be added in the SPARQL query in gpad-basic.rq: 'located_in', 'is_active_in'.
He also noticed we need to add the two relations to the PREFIX section at the top.
PREFIX located_in: <http://purl.obolibrary.org/obo/RO_0001025>
PREFIX is_active_in: <http://purl.obolibrary.org/obo/RO_0002432>

### PR DESCRIPTION
**Pull request by sierra-moxon**

### CODE REVIEW

**Comment by sierra-moxon** [comment]
@balhoff - reopened as PR on dev instead of master.

**Comment by dustine32** [comment]
@sierra-moxon Yeah, I bet this would work. Thanks!

**Comment by balhoff** [comment]
@vanaukenk @ukemi could you please also sign off on this? Asking because adding these has been pending for quite a long time and I'm not sure what has been holding it up, besides inertia.

**Review by balhoff — APPROVED** [review]
Looks good technically but I asked Kimberly and David to approve.

**Comment by sierra-moxon** [comment]
thanks so much @ukemi and @vanaukenk for taking a look.  As per @dustine32's great debugging, I hope this issue will help bring in the remaining noctua annotations to ZFIN (the testing revealed that they are getting left behind on roundtrip from ZFIN->noctua(one time import)->ZFIN. :)

**Comment by ukemi** [comment]
@balhoff do we have the right property chains in place? located_in o occurs_in -> is_active_in ? I think we need that, if not for the imports then for hand-curated models. You diff looks good to me.

**Comment by vanaukenk** [comment]
Thanks @balhoff 
I think I just have the same question as David about the property chain for the GPAD exports:  enables o occurs_in -> is_active_in

**Comment by balhoff** [comment]
- `enables o occurs_in -> is_active_in` => this is in RO
- There are some other axiom changes proposed in #179 that we should review. I don't think that should hold this change up.

**Pull request merged**
