### PR TITLE
Create replace_relations.tsv

### PR DESCRIPTION
**Pull request by vanaukenk**
Adding a file for @balhoff to review for replacing relations in GO-CAM models

### CODE REVIEW

**Comment by vanaukenk** [comment]
@balhoff 
Here's a draft tsv file for updating three of the RO relations used in GO-CAMs.  Will this work?
If not, please suggest what would be better.  Thx.

**Review by balhoff — APPROVED** [review]
That looks perfect to me. My only question is where we want this file to live. Should it be in noctua-models? We have an existing folder for SPARQL updates we've applied there: https://github.com/geneontology/noctua-models/tree/master/migrations 
cc @kltm

**Comment by vanaukenk** [comment]
Thanks, @balhoff 
@kltm - where should the two tsv files for non-automatic ontology updates live?

**Comment by kltm** [comment]
@vanaukenk I would suggest that this is noctua-models metadata, not minerva metadata.

**Comment by vanaukenk** [comment]
Okay.  I can upload the file to nocuta-models.  Is this the preferred directory:

https://github.com/geneontology/noctua-models/tree/master/migrations

If not, please let me know where the file should go.

Thx.

**Comment by kltm** [comment]
@vanaukenk I think that is a good place for that for the moment.

**Comment by kltm** [comment]
For https://github.com/geneontology/minerva/issues/465

**Comment by balhoff** [comment]
I think this can be closed now.

**Pull request closed without merging**
