### PR TITLE
Bugfixes on blazegraph conversion

### PR DESCRIPTION
**Pull request by goodb**
@kltm this version uses a different approach to handle search related to taxons.  It requires taxon information to be added to the models as a metadata parameter (like 'title') using the biolink:in_taxon property.  This seems to make things work much better but will require an update to the go-cam journal before launch.  Models saved with this system will include the taxon information.  This will do the update (it takes like 10 minutes for all the dev models):

minerva-cli.sh
--add-taxon-metadata
-j blazegraph-gocam-db.jnl
-ontojournal /tmp/blazegraph.jnl

### CODE REVIEW

**Comment by kltm** [comment]
@goodb Is this operation idempotent? If so, can we just add this along with `--import-owl-models` in a single command?

**Comment by goodb** [comment]
@kltm short answer no.  Would need to be done in two steps 1) build journal 2) run the update command on that journal.  Suppose we could tack it on to the code in 1) if you prefer.  

Another approach would be to do it outside pipeline and build etc.- just update the model files and issue a pr on noctua-models.  If you prefer that route, I can do it.

**Comment by kltm** [comment]
@goodb While we will have to work out the right timing to land this as desired, I think that the one time out-of-pipeline approach is probably the way to go, unless there's a good reason not to have this data persist in the TTL files? I'm open to adding required mechanism, but it seems like it's probably fine information to have in there if it's otherwise required anyways?

**Comment by goodb** [comment]
@kltm yes, I think there is no reason for this to live in the pipeline.  I think one time updates for model repos will do the trick - as long as that is followed by deployment of the new code that will add these to mew model saves.  Even then it wouldn't be hard to correct after the fact.

**Comment by cmungall** [comment]
Where is the best place to document this? In the ShEx?

I assume the cardinality is zero to many. 1 will be typical, but we will have multi-organism models, as well as template models.

**Comment by goodb** [comment]
@cmungall yes, should be added to shex.  And yes cardinality 0 to many .  *

**Comment by kltm** [comment]
@goodb Assuming these changes are safe with the current noctua-models `dev` (assuming so with *), you can go ahead and merge.

**Comment by goodb** [comment]
@cmungall actually just realizing that we don't have any place yet in the shex schema for documenting model-level metadata.  This would be new and probably should be done.

**Comment by kltm** [comment]
@goodb @cmungall It would be great to start on other aspects of models as well, such as required dating and users on model elements.

**Pull request merged**
