### PR TITLE
Add cli option to allow running checks against a graphstore journal.

### LINKED ISSUE #541: In some cases, minerva exits early exception when performing QC on graphstore
Recently, we discovered that minerva will bomb out when trying to QC the entire store. To reproduce:

* checkout minerva `master`
* enter repo root
* `wget http://skyhook.berkeleybop.org/blazegraph-go-lego-reacto-neo.jnl.gz`
* `gunzip blazegraph-go-lego-reacto-neo.jnl.gz`
* `wget http://skyhook.berkeleybop.org/snapshot/products/blazegraph/blazegraph-internal.jnl.gz`
* `gunzip blazegraph-internal.jnl.gz`
* `reset && MINERVA_CLI_MEMORY=12G ./minerva-cli/bin/minerva-cli.sh --validate-go-cams --shex -i blazegraph-internal.jnl -r /tmp/ --ontojournal blazegraph-go-lego-reacto-neo.jnl`

Errors are like:

```
08:49:30  2024-05-08 08:49:30,161 INFO  (org.geneontology.minerva.cli.CommandLineInterface:1104) preparing model stats...
08:49:30  java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
08:49:30  	at com.google.common.base.Absent.get(Absent.java:47)
08:49:30  	at org.geneontology.minerva.model.GoCamModel.<init>(GoCamModel.java:49)
08:49:30  	at org.geneontology.minerva.cli.CommandLineInterface.validateGoCams(CommandLineInterface.java:1107)
08:49:30  	at org.geneontology.minerva.cli.CommandLineInterface.main(CommandLineInterface.java:406)
08:49:30  2024-05-08 08:49:30,182 INFO  (org.geneontology.minerva.cli.CommandLineInterface:1266) done with validation
```

Trying to patch some of these up with exception handling didn't really work as it's a more fundamental issue that the models are not always containing the expected identifier. E.g.

```
2024-05-08 14:42:15,902 INFO  (org.geneontology.minerva.json.InferenceProvider:82) Done with shex validation. model is conformant is: false
java.lang.NullPointerException
	at org.geneontology.minerva.validation.ShexValidationReport.getAsTab(ShexValidationReport.java:69)
	at org.geneontology.minerva.cli.CommandLineInterface.validateGoCams(CommandLineInterface.java:1204)
	at org.geneontology.minerva.cli.CommandLineInterface.main(CommandLineInterface.java:406)
2024-05-08 14:42:16,582 INFO  (org.geneontology.minerva.cli.CommandLineInterface:1269) done with validation
```

 We need to either

* fix the core functionality to not expect this
* add this info to the models

### PR DESCRIPTION
**Pull request by balhoff**
New CLI option `--check-graph-type`. Fixes #541.

### CODE REVIEW

**Review by kltm — APPROVED** [review]
Adds a default "off" flag that will bypass certain problematic models--from the POV of QC; if "on", it will skip anything that doesn't have the appropriate data.

I just want to confirm that the `->` operator is Java 8?
```
                    if (gocam.getAnnotations().stream().noneMatch(annotation ->
                            annotation.getProperty().getIRI().equals(graphType)
```

**Comment by kltm** [comment]
Noticing that tests did not pass?

**Comment by balhoff** [comment]
I will look at the tests—they are unfortunately sensitive to changing external data.

**Comment by balhoff** [comment]
> Adds a default "off" flag that will bypass certain problematic models--from the POV of QC; if "on", it will skip anything that doesn't have the appropriate data.
> 
> I just want to confirm that the `->` operator is Java 8?
> 
> ```
>                     if (gocam.getAnnotations().stream().noneMatch(annotation ->
>                             annotation.getProperty().getIRI().equals(graphType)
> ```

Java 8!

**Comment by balhoff** [comment]
Test failure relates to website problems at biopax.org. Fix at #543.

**Comment by balhoff** [comment]
> Adds a default "off" flag that will bypass certain problematic models--from the POV of QC; if "on", it will skip anything that doesn't have the appropriate data.

@kltm one thing to note—don't use this flag if testing the actual Minerva database. The models there don't have this annotation, which is inserted by the graphstore build.

**Comment by kltm** [comment]
> > Adds a default "off" flag that will bypass certain problematic models--from the POV of QC; if "on", it will skip anything that doesn't have the appropriate data.
> 
> @kltm one thing to note—don't use this flag if testing the actual Minerva database. The models there don't have this annotation, which is inserted by the graphstore build.

@balhoff Not that I was planning on changing the flags for our production Noctua stuff, but wouldn't that check be safe when looking at just a "TTL models only" store?

**Comment by balhoff** [comment]
@kltm in a TTL models only store, all of them would get skipped if you use that flag. They won't contain the triple `?ont :graphType :noctuaCam`.

**Comment by kltm** [comment]
@balhoff Ah, I think I understand: the trick is that they are marked in the "extended" store, but not so in the "noctua" one, and you're using that as the criteria?

**Comment by balhoff** [comment]
Yes.

**Pull request merged**
