### PR TITLE
Shex validation

### PR DESCRIPTION
**Pull request by goodb**
Adds a shex validation step when the reasoner flag is on.  Look for information coming back in the response object:
response.data.unconformantFlag 
response.data.nonconformant_uris 
response.message 

Although the change is stuck in next to the reasoner process, it works independently.  e.g. it will still run when the model is inconsistent.  This works because it gets superclass information from a sparql query to rdf.geneontology.org .  If we changed the schema to look at types on individuals with the expectation that they would be fully expanded, then we could read those in from the reasoner without the external call.  (Noting that Arachne does not provide subclass expansion, just node typing).  It also downloads the schema from the GO_Shapes repository on startup, hence it needs net access to work.

### CODE REVIEW

**Comment by goodb** [comment]
I don't think the code changes have anything to do with the Travis failure.  It seems that we need to update the travis test to point to a newer version of java - probably the openjdk one that is used on the real server.

**Comment by kltm** [comment]
@goodb I'm trying to update that, just to be sure.

**Comment by kltm** [comment]
@goodb I'm having an issue at runtime: 
```
java -Xmx64G -jar ../minerva/minerva-cli/bin/minerva-cli.jar --import-owl-models -j /tmp/blazegraph.jnl  -f ~/local/src/git/noctua-models/models/
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:330)
	at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:263)
	at java.util.jar.JarVerifier.processEntry(JarVerifier.java:318)
	at java.util.jar.JarVerifier.update(JarVerifier.java:230)
	at java.util.jar.JarFile.initializeVerifier(JarFile.java:383)
	at java.util.jar.JarFile.ensureInitialization(JarFile.java:612)
	at java.util.jar.JavaUtilJarAccessImpl.ensureInitialization(JavaUtilJarAccessImpl.java:69)
	at sun.misc.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:991)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:451)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```
Fine before merge.

Is there a ticket we should tag the PR onto?

**Comment by goodb** [comment]
#212

**Pull request merged**
