### PR TITLE
Add regulates_o_occurs_in to whitelist

### PR DESCRIPTION
**Pull request by cmungall**
See https://github.com/geneontology/noctua-models/issues/44

### CODE REVIEW

**Comment by vanaukenk** [comment]
@balhoff - can you remind me where the whitelist of relations lives?  Thx.

**Comment by balhoff** [comment]
@vanaukenk it's the file that Chris edited in this pull request. Here: https://github.com/geneontology/minerva/blob/master/minerva-converter/src/main/resources/org/geneontology/minerva/legacy/sparql/gpad-extensions.rq

**Comment by balhoff** [comment]
+1

**Comment by vanaukenk** [comment]
@balhoff - thank you!  Sorry, I should have looked at the Files changed link.....

**Pull request merged**
