### PR TITLE
Include triple reading-order fix from OWL API (release version)

### PR DESCRIPTION
**Pull request by balhoff**
An official OWL API release is now available containing the bug fix related to #82. This pull request does not contain other changes in progress such as modifications to handling of empty external lookup service results. So, we should merge this change and deploy ASAP.

### CODE REVIEW

**Comment by cmungall** [comment]
+1

**Comment by cmungall** [comment]
Hopefully there will be a 4.2.9 release soon

**Comment by cmungall** [comment]
ignore my last comment, I see there is now a release

**Comment by kltm** [comment]
Just to clarify, the extra build steps are no longer needed?

**Comment by balhoff** [comment]
Yes that is correct.

**Pull request merged**
