### PR TITLE
DO NOT MERGE Doc fixes, /status endpoint, use of catalog.xml during tests.

### PR DESCRIPTION
**Pull request by DoctorBud**
- Added env variable detection for GENEONTOLOGY_CATALOG and
  MINERVA_MAVEN_OPTS to deal with faster cached behavior and offline
code.berkeleybop.org during unit tests. Production versions of Minerva get their configuration via the command-line options still.
- Added some scripts that might be helpful to future Minerva-nauts.
- Ensure that the tests respect the GENEONTOLOGY_CATALOG env var, which
  massively speeds up unit tests.
- Adds --help and --version commands to CLI.
- Adds /status and /memstatus endpoint, both of which do the same thing right now.
- Adds single-file webpage test for Minerva.
- fixes NOCTUA_MODELS defn for startServerExample.sh.

### CODE REVIEW

**Comment by hdietze** [comment]
I'm all in favor for improvements of the tests and documentation.
But I don't like to pollute the batch handler. It's already a beast and adding yet another aspect makes it more complicated. It would like to see status (and maybe more management later) as a separate interface and implementation. This should also help to remove all the fake-id stuff and using the error code path to return the status result.

**Comment by DoctorBud** [comment]
Agreed, Heiko. It's leftover from when I was doing memory testing. I think every webapp should have a /status endpoint, but this one belongs elsewhere. I will either remove it or relocate it (the m3BatchStatus endpoint). Don't merge the PR until I fix it.

**Comment by DoctorBud** [comment]
I added a StatusHandler.java and moved the `m3BatchStatus` into there. I broke it up into two endpoints, a `/status` endpoint that returns TEXT and a `/memstatus` endpoint that returns JSON. In both cases, the actual content is just a pre and post-GC memory dump. I will expand upon this as needed (e.g., version, timestamp, config).

**Comment by kltm** [comment]
@DoctorBud We've been moving towards a more uniform format for our service statuses; not finished yet, but with an eye towards slotting into a general monitor later on and having possibly a uniform access/response library. For example:

 http://noctua.berkeleybop.org/status
 http://barista.berkeleybop.org/status

It would be nice to use those as a template, at least for /status.

**Comment by cmungall** [comment]
What does standard mean here? The payload isn't very self-explanatory, no link to a schema.

Seems to be roughly the same json schema as:
http://monarchinitiative.org/status

But the schema is really just a property-value model.

If we're serious about having a standard payload, then shouldn't we either de-reify the properties so they are json properties, or have a standard ontology of annotation properties

**Comment by kltm** [comment]
@cmungall Yes, they're all related. I can't find all the discussion, but the start of adding it to monarch is here: https://github.com/monarch-initiative/monarch-app/issues/630
The idea would be to get /status more-or-less the same everywhere--a JSON blob of similar structure. When we first discussed this it was in the context of enabling easy uniform service monitoring with a little sugar. I think having an ontology of annotation properties would be overkill.

**Comment by DoctorBud** [comment]
This PR is sort of non-essential and was motivated by my early attempts to debug and figure out Minerva. Now that I have grokked Noctua/Barista/Minerva and have a new place to put the WebPhenote customizations, I may just leave this hanging until I need to debug Minerva again. Some of the features that might be salvageable include:
- Unit tests can now use a catalog.xml for faster throughput via an environment variable.
- There's a /status endpoint
- There's a --version and a --help option, but they don't do much.
- The documentation is improved in some ways, but may be distracting in terms of how to obtain the proper mirrored OWL models. I've learned much since I wrote this stuff.

**Comment by cmungall** [comment]
@DoctorBud I started refactoring the tests to use only minimal modules (removing dependency on loading go-lego over the wire), and a catalog #48

I'll take a look the doc stuff and see what can be moved over - docs are always welcome.

I'll leave it to you and @kltm and later @balhoff what is required re /status endpoint

**Pull request closed without merging**
