### PR TITLE
Run command-line GPAD export in parallel.

### PR DESCRIPTION
**Pull request by balhoff**

### CODE REVIEW

**Comment by balhoff** [comment]
@kltm should we merge this? Did you ever try running it in the pipeline?

**Comment by kltm** [comment]
No, we've been holding on the `release` going out before making changes. While the release is prepped and ready, some data errors were found and it's awaiting explanation.

**Comment by kltm** [comment]
`release` has passed.

**Comment by kltm** [comment]
Also noting https://github.com/geneontology/pipeline/issues/139

**Pull request merged**
