### PR TITLE
code and test for exact match text search

### PR DESCRIPTION
**Pull request by goodb**

### CODE REVIEW

**Comment by goodb** [comment]
@kltm this is failing travis because of some change to http://skyhook.berkeleybop.org/blazegraph-go-lego-with-reacto.jnl.gz  
I don't have time to diagnose further till tomorrow.  But.. if you are working on that, you can run the minerva build to make sure its working..

**Comment by kltm** [comment]
Huh. I had thought that the product of that pipeline should be correct, but I'll need to dig in. Unfortunately, I've got two other pipeline I'm working on today and might not make it.

**Comment by goodb** [comment]
@kltm I believe it is missing neo.owl. This was previously included in go_lego.owl and now will need to be added to the blazegraph journal in an additional step.

**Comment by goodb** [comment]
@tmushayahama @vanaukenk  FYI on current behavior here.  The "exact match" here is performed only on individual tokens, not the whole title.  (Sorry learning as I go here).  For example when searching over the reactome models

searching like this: http://127.0.0.1:6800/search/?title=*Antigen*
results including titles containing words with antigen in them like:
Reactome:unexpanded:Cross-presentation of soluble exogenous antigens (endosomes)

searching like this: http://127.0.0.1:6800/search/?title=Antigen 
will only get models where the title has the exact (ignoring case) search term like:
Reactome:unexpanded:MHC class II antigen presentation

So.. for now I suspect default to the * search with the current set up (that requires all tokens present) ought to work pretty well.  If we really need true exact match search over the titles, this can be added easily.

**Pull request merged**
