### PR TITLE
Updating production Minerva

### PR DESCRIPTION
**Pull request by tmushayahama**
@kltm I believe this is what is powering the dev server. This PR will be the one for ART production as tested by @vanaukenk and @ukemi @lpalbou

### CODE REVIEW

**Comment by kltm** [comment]
@balhoff Odd that some tests were not successful, but I guess that was a known issue, correct?

**Comment by balhoff** [comment]
> @balhoff Odd that some tests were not successful, but I guess that was a known issue, correct?

Not known to me!

**Comment by kltm** [comment]
Ha--neat! I guess we'll see what happens. It seems to be passing now anyways. Huh.

**Comment by lpalbou** [comment]
And cheers for random code outcome ! I have not looked at the error, could it be a network issue ?

**Pull request merged**
