### PR TITLE
Compact test ontology file (go-lego-module.omn.gz)

### PR DESCRIPTION
**Pull request by yy20716**
As discussed in [this thread](https://github.com/geneontology/minerva/issues/57#issuecomment-333004631), I cut out irrelevant ontological axioms such as the ones not listed in the 
[M3ExpressionParserTest](https://github.com/geneontology/minerva/blob/master/minerva-server/src/test/java/org/geneontology/minerva/server/handler/M3ExpressionParserTest.java). 
   - From my observation, other testcases do not use the compressed ontology file (go-lego-module.omn.gz), so except the resources listed in that test, I removed extra axioms in the ontology file. 
   - This compaction will lead to reducing the size of the output log and therefore travis would work again.

### CODE REVIEW

**Comment by kltm** [comment]
@yy20716 
Does this also clear https://github.com/geneontology/minerva/issues/57 ?

**Comment by yy20716** [comment]
* It was supposed to clear up that issue but the tests are failing again. When I checked Travis [build logs](https://travis-ci.org/geneontology/minerva/builds/282990215?utm_source=github_status&utm_medium=notification), it was not failing due to M3ExpressionParser but due to the other unittest, i.e.,
 
> Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.016 sec <<< FAILURE! - in org.geneontology.minerva.server.handler.BatchModelHandlerTest
> org.geneontology.minerva.server.handler.BatchModelHandlerTest  Time elapsed: 0.016 sec  <<< FAILURE!
> java.lang.AssertionError: We expect at least 4GB for the max memory, current: 1908932608

* It seems that the testcodes in [BatchModelHandler](https://github.com/geneontology/minerva/blob/master/minerva-server/src/test/java/org/geneontology/minerva/server/handler/BatchModelHandlerTest.java) expliclity checks whether the node that runs this test has at least 4GB memory but I guess the node that runs trevis does not have enough memory.

**Comment by kltm** [comment]
Bleh. We should split out some of the heavier tests and hook them into our Jenkins.

**Comment by yy20716** [comment]
* Ok. Can you please suggest what I should or can do next? I wonder whether we have separate nodes that run Jenkins. Maybe would it be better for now to switch to other tasks?

**Comment by kltm** [comment]
I started something in `jenkinsfilie-test, but haven't had a chance to test and complete. We can talk more about it on Friday (assuming I wake up in time).

**Comment by balhoff** [comment]
I removed that memory check and the current tests seem to run fine on Travis.

**Pull request merged**
