### PR TITLE
GROUP BY only model id.

### PR DESCRIPTION
**Pull request by balhoff**
Use aggregates for everything else, in order to align number of results returned with the number of matching models. Addresses #370

### CODE REVIEW

**Comment by tmushayahama** [comment]
@balhoff I tested and it seems to be working and @lpalbou https://github.com/geneontology/minerva/issues/370 now brings correct count.

@kltm can you merge this so that @ukemi @vanaukenk can doo more tests

I will continue to test as see if no side effect

**Comment by lpalbou** [comment]
It the counts are now correct, that's good enough for me ! Thanks everyone

**Comment by lpalbou** [comment]
@balhoff do you think this fix will slow down the search ?

@tmushayahama while this gets deployed to prod, if you want to do more tests, the test set should contain large models with several occurrences of the same terms - that's where the search was failing due to limit/pagination on occurrences rather than models. Thanks

**Comment by kltm** [comment]
Ready to go to dev.

**Comment by balhoff** [comment]
> @balhoff do you think this fix will slow down the search ?

I don't think so.

**Comment by tmushayahama** [comment]
@balhoff @lpalbou I think there is now a bug that the results are not sorted by date DESC. I think now its hard to find models

**Pull request merged**
