### PR TITLE
added support for sonarqube

### PR DESCRIPTION
**Pull request by abessiari**
1. changed config for javadoc plugin so that we do not have to use -Dmaven.javadoc.skip=true
2. added jacoco plugiin

### CODE REVIEW

**Comment by kltm** [comment]
@balhoff Does this look good to you?

**Comment by abessiari** [comment]
@balhoff 

I am moving the version of jacoco to parent pom and doing another round of testing. it takes a little time to run tests I should know soon.

**Comment by balhoff** [comment]
> @balhoff Does this look good to you?

I think so but I don't know anything about these plugins. What are sonarqube and jacoco for?

**Comment by abessiari** [comment]
Hi Jim.

Sonarqube is used for viewing static analysis (code smells, bugs, ...) and
code coverage reports (percentage of lines covered by unit tests, covered
lines, lines that are not covered)
Please see below for a quick install and testing
Thanks
aes

To test the poms quickly you can use the minerva-lookup since the tests do
not take a long time.

1) run sonarqube locally using docker.
>docker run -d --name sonarqube -p 9000:9000 sonarqube:latest
2) go to minerva-lookup

>cd minerva-lookup

>mvn clean package sonar:sonar

3) On browser http://localhost:9000 to view the reports.

   username:admin password:admin

**Comment by balhoff** [comment]
@abessiari thanks! I gave it a try an ran into one issue:

```
[ERROR] Failed to execute goal on project minerva-lookup: Could not resolve dependencies for project org.geneontology:minerva-lookup:jar:0.6.1: Could not find artifact org.geneontology:minerva-core:jar:0.6.1 in oss-sonatype-snapshot (https://oss.sonatype.org/content/groups/public) -> [Help 1]
```

Do I need to do an install first?

**Comment by abessiari** [comment]
@balhoff
Yes you need to do an install from the top level.  You should not need to use -Dmaven.javadoc.skip=true anymore.
` mvn package -DskipTests`

**Comment by balhoff** [comment]
@abessiari I am having trouble getting this to work. Here are my issues:
- I still have to use `-Dmaven.javadoc.skip=true`
- When I am running the docker container and then run `mvn clean package sonar:sonar`, I get this:
 
```
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.8.0.2131:sonar (default-cli) on project minerva-lookup: Unable to execute SonarScanner analysis: Fail to parse entry in bootstrap index: <!doctype html><html lang="en"><head><meta http-equiv="content-type" content="text/html; charset=UTF-8" charset="UTF-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge"><link rel="apple-touch-icon" href="/apple-touch-icon.png">
...
```

I trimmed it; it's HTML text with a bunch of CSS.

**Comment by abessiari** [comment]
@balhoff 
Humm. I am assuming you are using the sonarqube branch. We can do a quick zoom meeting.
 I am available this morning.
Thanks

**Comment by abessiari** [comment]
@balhoff 
I did a quick search. Please make sure sonar server is fully initialized and ready. http://localhost:9000

**Comment by balhoff** [comment]
Thanks @abessiari, I sent you a message in BBOP slack.

**Comment by abessiari** [comment]
FYI: I did a clean build on a fresh machine and did not have to specify -Dmaven.javadoc.skip=true

root@28e915de0027:/minerva# history
    1  git clone https://github.com/geneontology/minerva.git
    2  cd minerva/
    3  git checkout -b sonarqube
    4  mvn package install -DskipTests

**Review by balhoff — CHANGES_REQUESTED** [review]
@abessiari helped me get it running; I was making a couple of silly mistakes. We agreed he would add a section on sonarqube under Testing in https://github.com/geneontology/minerva/blob/master/INSTRUCTIONS.md

**Comment by abessiari** [comment]
@balhoff 
Done. Nice chat this morning.

**Review by balhoff — APPROVED** [review]
Looks good, thanks.

**Pull request merged**
