### PR TITLE
Model measurements

### PR DESCRIPTION
**Pull request by goodb**
upgrade to owl api 4.5.15 from 4.5.13
Add gocam stat calculation to command line validation.

### CODE REVIEW

**Comment by kltm** [comment]
@goodb Good to go to `dev`? Is there something you want you to demonstrate here soon?

**Comment by goodb** [comment]
@kltm lets let the changes I just pushed weave through travis test before merging.  

Right now, the only impact of these changes should be on the command line validation routine.  (Though the owl api upgrade likely cures some other unknown weirdnesses like the one that was killing me last week.)  It will produce a much more detailed report about the model collection that it is fed.  I'm using this to prepare information for the reactome paper but I believe it is generally useful for batch understanding of model collections.

**Comment by kltm** [comment]
@goodb Taking a quick look at all the changes, I was wondering if one of them was the proposed (https://github.com/geneontology/minerva/issues/335#issuecomment-668999811) fix for `model-state`?

**Comment by goodb** [comment]
Yes, the important change for that issue (as shown in https://github.com/geneontology/minerva/pull/341 ) is in there.

**Comment by kltm** [comment]
@goodb If there is nothing more here, I'll merge. Would there be any issue with this going into `master`, anything that might affect the API? I'd ideally like to get this through to `master` to get the fix out in the pipeline for the `model-state` issue.

**Comment by goodb** [comment]
@kltm I think it ought to be fine.  Lets cycle dev and give it a quick manual check there first though, okay ?

**Pull request merged**
