### PR TITLE
Fix for failure for reasoner to update after undo

### PR DESCRIPTION
**Pull request by balhoff**

### CODE REVIEW

**Comment by kltm** [comment]
@balhoff Assuming @cmungall accepts the PR, do you feel comfortable with this fix going in hot just before the meeting?

**Comment by balhoff** [comment]
The existing unit tests pass but it may be a little risky without some more interactive testing. Depends how much the bad reasoner experience with undo/redo is impacting people. I would say there's very little chance for breakage except for one thing: this will now mark the ModelContainer as 'modified' after an undo, which wasn't happening before. That itself may have been the source of some odd behavior.

**Comment by kltm** [comment]
As the current undo/redo-reasoner combo pretty much breaks the system, likely anything would be better, but depending on how the code is setup, I could imagine there could be risks. I'm just wondering if you would feel more comfortable to wait a week or if you think that we can test as we go during the workshop. Worst case is we revert, but if there is a possibility of something leaking out...

**Comment by kltm** [comment]
It sounds like you're pretty confident though. I think then that if Chris is okay, I'll go ahead an pout it out during the next quiet time.

**Comment by balhoff** [comment]
Go for it.

**Pull request merged**
