### PR TITLE
fix ordering for model search

### PR DESCRIPTION
**Pull request by goodb**
cured an issue where repeated identical searches produced differently ordered results.

### CODE REVIEW

**Comment by kltm** [comment]
Neat--just a type difference.

**Comment by tmushayahama** [comment]
@goodb thanks, so all this time it was only the Java Data structure not sparql. That's better then. 

Here a manual testing case if you want to debug code. @kltm @vanaukenk from the workbench call on some ways to test search. I haven't found any automated way. Any ideas?

## Test Case 1: Check if same results

### Steps

1. Filtering by state = review  gives a small dataset (8 results total)
2. Reduce page size to 3
3. Search 3+ times on separate instance using http://barista-dev.berkeleybop.org/search?offset=0&limit=3&state=review

### Expected 
All searches should give same result set regardless of order

### Actual

**1st instance**
image

**2nd instance** 
image

**3rd instance**
image

## Test Case 2: Check if results in test 1 doesn't appear in Test 2

### Steps

1. Same setup as Test 1
2. Offset to 3 to get the rest of the results (5 results) using http://barista-dev.berkeleybop.org/search?offset=3&limit=5&state=review

### Expected
all the models ids in Test should not appear in Test 2

### Actual
http://barista-dev.berkeleybop.org/search?offset=3&limit=5&state=review
image

**Comment by goodb** [comment]
@tmushayahama @kltm somehow the search now live on barista-dev there doesn't have a recent update to the sparql query template. https://github.com/geneontology/minerva/blob/dev/minerva-server/src/main/resources/ModelSearchQueryTemplate.rq   Its acting like it was pulled from master and not dev.  

If you look at the response, the sparql block should finish with  ORDER BY desc(?date) desc(?id) but the live server doesn't have the desc(?id) .  Note that all of your dates in the first test example are identical.  Without the additional ordering from the model id, results will be inconsistent.

**Comment by kltm** [comment]
@goodb 
I've updated noctua-dev again.

**Pull request merged**
