### PR TITLE
Dump model on each save.

### PR DESCRIPTION
**Pull request by balhoff**
For #502.

### CODE REVIEW

**Comment by kltm** [comment]
@balhoff Do I want to re-deploy on noctua-dev on the minerva `dev` branch?

**Comment by balhoff** [comment]
> @balhoff Do I want to re-deploy on noctua-dev on the minerva `dev` branch?

You could, but I only updated test code.

**Comment by balhoff** [comment]
@kltm tests are passing now.

**Comment by kltm** [comment]
@vanaukenk I'd vote to have this on the docket for the Dec 1 outage.

**Comment by kltm** [comment]
@balhoff Tested from my end, looks good!

**Pull request merged**
